---
title: "Tarea_Programada_02_JimenaRamirez"
author: "Jimena Ramirez Zamora"
date: "2024-06-09"
output: html_document
---

```{r}
install.packages("mtcars")
datos_mtcars<-mtcars
datos_mtcars
library(dplyr)
install.packages("DT")
library(DT)
str(mtcars)
summary(mtcars)

```
```{r}
##histograma para millas por galón
data("mtcars")
hist(mtcars$mpg ,main="Optimización de Millas por galón a través del Análisis de Datos",
     xlab= "millas por galón",
     col="thistle1",
     freq=TRUE)
```

```{r}
##boxplot
data("mtcars")
boxplot(mtcars$mpg~mtcars$cyl,main= "Relación entre el Número de Cilindros y las Millas por Galón",
        xlab="Número de Cilindros",
        ylab="millas por galón",
        col="darkseagreen1",
        border="darkseagreen",
        horizontal = TRUE,
        notch=TRUE)
```

```{r}
##dispersión
data("mtcars")
plot(mtcars$hp,mtcars$mpg,
     main = "Relación entre Caballos de Fuerza y las Millas por Galón",
     xlab = "Caballos de Fuerza",
     ylab= "Millas por Galón ",
     pch=20)
       
```

```{r}
##gráfico de barras
data("mtcars")
cilindros<-table(mtcars$ncyl)
barplot(cilindros,main="Distribución de vehículos por Categoría de Cilindros",
        xlab="Distribución de vehículos ",
        ylab="Categoría de Cilindros",
        col="plum2",
        horiz=TRUE)

```

##Estadística descriptiva
```{r}
data("mtcars")
media<-mean(mtcars$mpg)
media
```
```{r}
data("mtcars")
mediana<-median(mtcars$mpg)
mediana
```
```{r}
data("mtcars")
varianza<-var(mtcars$mpg)
varianza
```
```{r}
data("mtcars")
desviación_estándar<-sd(mtcars$mpg)
desviación_estándar
```
##tabla de contigencia
```{r}
data("mtcars")
tabla_contigencia<-table(mtcars$cyl,mtcars$gear)
tabla_contigencia

```
##Estadística inferencial
```{r}
t.test(mtcars$mpg,mu=20)
```
#prueba de correlación de Pearson
```{r}
cor.test(mtcars$hp,mtcars$mpg,method = "pearson")
```

